version: '3'

services:
  app:
    image: "tmknra/concept_crm-dev:latest"
    container_name: ConceptCRMApplication
    depends_on:
      - db
    ports:
      - "8081:8081"
    env_file: .env
  db:
    image: 'postgres:14-alpine'
    container_name: db
    ports:
      - "5432:5432"
    env_file: .env
    restart: always