version: '3'

services:
  app:
    image: "tmknra/concept_crm-dev:latest"
#    build:
#      context: .
    container_name: ConceptCRMApplication
    depends_on:
      - postgres
    ports:
      - "8081:8081"
    env_file: .env
  postgres:
    image: 'postgres:14-alpine'
    container_name: db
    ports:
      - "5432:5432"
    env_file: .env