version: '2'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ConceptCRMApplication
    depends_on:
      - db
    env_file: .env
    ports:
      - "8001:8001"


  db:
    image: 'postgres:14-alpine'
    container_name: db
    env_file: .env
    ports:
      - "5432:5432"
