name: Stage

on:
  push:
    branches: [ dev ]
  workflow_dispatch:

env:
  CONTAINER_NAME: concept-backend-dev
  IMAGE_NAME: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.event.repository.name }}-dev

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      #      - uses: actions/checkout@v3
      #      - uses: actions/setup-java@v3
      #        with:
      #          distribution: 'temurin' # See 'Supported distributions' for available options
      #          java-version: '17'
      #      - run: java -cp java ConceptCRMApplication

      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - run: chmod +x ./gradlew
      - run: ./gradlew build --no-daemon

  shipping:
    name: Prepare docker image
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  deploy:
    name: Staging deploy
    runs-on: ubuntu-latest
    needs: shipping
    steps:
      - name: Executing remote command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          script: |
            docker pull ${{ env.IMAGE_NAME }}:latest && 
            docker-compose up --no-deps --force-recreate -d --build app
