name: Stage

on:
  push:
    branches: [ dev ]
  workflow_dispatch:

env:
  CONTAINER_NAME: concept-backend-dev
  IMAGE_NAME: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.event.repository.name }}-dev

jobs:
  deploy:
    name: Staging deploy
    runs-on: ubuntu-latest
#    needs: shipping
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: copy file via ssh key
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          source: "docker-compose.yaml"
          target: "backend"
      - name: Executing remote command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          script: |
            cd backend &&
            docker pull ${{ env.IMAGE_NAME }}:latest && 
            docker-compose up -d
